export const SET_SETTING = 'SET_SETTING';
export const SET_TITLES = 'SET_TITLES';
export const ADD_PRESET = 'ADD_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const CHANGE_ACTIVE_PRESET = 'CHANGE_ACTIVE_PRESET';
